---
- name: configuring /etc/sysconfig/network-scripts/ifcfg-eth0
  replace:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: '^DEFROUTE.*=.*'
    replace: "DEFROUTE=no"

- name: configuring /etc/sysconfig/network-scripts/ifcfg-eth0
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "DEFROUTE=no"
    state: present

- name: ifcfg provision from template
  template:
    backup: true
    owner: root
    group: root
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: ifcfg-vlan1.j2, dest: "/etc/sysconfig/network-scripts/ifcfg-{{ config_device }}.{{ vlanid_1 }}" }
  notify: restart_network
...