# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.memory = 1280
    v.cpus = 2
  end

  config.vm.define "webhost" do |webhost|
    webhost.vm.network "private_network", adapter: 2, :device => "eth1", ip: "192.168.11.175"
    webhost.vm.hostname = "webhost"
  end

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    mkdir -p ~root/.ssh
    cp ~vagrant/.ssh/auth* ~root/.ssh
    #cat /vagrant/id_rsa.pub | awk '{print $1,$2}' >> /root/.ssh/authorized_keys
    ip route add 192.168.69.0/24 via 192.168.11.1 dev eth1 2>&1 >/dev/null || true
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible_repo/startall.yml"
    ansible.verbose = "true"
    #ansible.become = "true"
  end

end
