---
- name: packages install # Ставим нужные пакеты.
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - ntp
    - tzdata
    - ipa-client

- name: disable chronyd # Выключим chrony.
  systemd:
    name: chronyd
    enabled: false

- name: set timezone # Задаём часовой пояс.
  timezone:
    name: "{{ ntp_timezone }}"

- name: enable ntpd # Рестартим NTP.
  systemd:
    name: ntpd
    state: restarted
    enabled: true

- name: hostname # Зададим машине нужное имя.
  hostname: 
    name: "{{ hostname }}.{{ domain }}"

- name: hosts # Подправим Hosts: заменим 127.0.0.1 на реальный адрес с соотнесём его с fqdn
  replace:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1(\s+){{ hostname }}(\s+){{ hostname }}.*'
    replace: "{{ my_ip }} {{ hostname }}.{{ domain }} {{ hostname }}"
    backup: yes # Бекап!

- name: hosts # Подставим сервер FreeIPA на всякий случай (вдруг DNS упадёт?)
  lineinfile:
    path: /etc/hosts
    line: "{{ ipa_ip }} {{ servername }}.{{ domain }} {{ servername }}"

- name: ipa-client # Установим FreeIPA клиент с нужными настройками
  ignore_errors: true
  shell: "ipa-client-install -U --mkhomedir --enable-dns-updates --principal={{ principal }} --password={{ password }} --domain={{ domain }} --server={{ servername }}.{{ domain }} --realm={{ realm }}"

- name: create test non-admin user # Создадим тестового пользователя с ключами
  user:
    name: "{{ username }}"
    password: "{{ userpassword | password_hash('sha512') }}" 
    state: present
    update_password: on_create
    create_home: yes
    generate_ssh_key: yes

- name: read new user keys # Занесём сгенерированные ключи новго пользователя в переменную
  shell: cat /home/{{ username }}/.ssh/id_rsa.pub
  register: userkey

- name: add new user to LDAP # Создадим нового пользователя в LDAP на основе ранее созданного локального пользоватея
  ignore_errors: true
  ipa_user:
    name: "{{ username }}"
    state: present
    givenname: "{{ givenname }}"
    sn: "{{ sn }}"
    mail:
    - "{{ mail }}"
    telephonenumber:
    - "{{ tel }}"
    sshpubkey:
    - "{{ userkey.stdout }}" # Сюда подставим ранее сгенерированный ключ.
    ipa_host: "{{ servername }}.{{ domain }}"
    ipa_user: "{{ principal }}"
    ipa_pass: "{{ password }}"  
...