# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 2048
	  v.cpus = 2
  end

  config.vm.define "replica" do |replica|
    replica.vm.network "private_network", adapter: 2, :device => "eth1", ip: "192.168.11.161"
    replica.vm.hostname = "replica"
  end

  config.vm.define "master" do |master|
    master.vm.network "private_network", adapter: 2, :device => "eth1", ip: "192.168.11.160"
    master.vm.hostname = "master"
  end

  config.vm.provision "shell", run: "always", inline: <<-SHELL
    mkdir -p ~root/.ssh
    cp ~vagrant/.ssh/auth* ~root/.ssh
    #cat /vagrant/id_rsa.pub | awk '{print $1,$2}' >> /root/.ssh/authorized_keys
  SHELL

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "ansible_repo/startall.yml"
    ansible.verbose = "true"
    #ansible.become = "true"
  end

end
