---
all:
  children:
    vms:
      hosts:
        vm1:
          ansible_host: 192.168.11.126
        vm2:
          ansible_host: 192.168.11.127
        vm3:
          ansible_host: 192.168.11.128
...
