---
all:
  children:
    webservers:
      hosts:
        web:
          ansible_host: 192.168.11.119
    logservers:
      hosts:
        log:
          ansible_host: 192.168.11.120
        elk:
          ansible_host: 192.168.11.121
...
