---
- name: enable auditd listen port # Слушаем auditd порт 60
  replace:
    path: /etc/audit/auditd.conf
    regexp: '^##tcp_listen_port = 60'
    replace: "tcp_listen_port = 60"
  notify: restart_auditd
...
