# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuspam => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.116'
		},
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "256"]
                  needsController = false
		  end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              yum install epel-release -y -q 2>/dev/null
              yum install ansible vim -y -q 2>/dev/null
	      cd /vagrant/ansible_repo/
	      ansible-playbook startall.yml
          SHELL
#          box.vm.provision "ansible" do |ansible|
#              ansible.playbook = "ansible_repo/startall.yml"
#              end
      end
  end
end

