---
- name: install openvpn
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - openvpn

- name: install configs from template
  template:
    backup: true
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: client_tap.conf.j2, dest: "{{ ovpn_client_config_path }}client_tap.conf" }
    - { src: client_tun.conf.j2, dest: "{{ ovpn_client_config_path }}client_tun.conf" }

- name: Fetch CA certificate from server to localhost /tmp
  fetch:
    src: "{{ pki_CA_certs_path }}{{ CA_cert_name }}"
    dest: /tmp
  delegate_to: server

- name: Copy CA certificate from localhost to client
  copy:
    src: "/tmp/{{ hostname }}/{{ pki_CA_certs_path }}{{ CA_cert_name }}"
    dest: "{{ pki_CA_certs_path }}{{ CA_cert_name }}"

- name: Remove CA certificate from localhost /tmp
  file:
    path: "/tmp/{{ hostname }}/{{ pki_CA_certs_path }}{{ CA_cert_name }}"
    state: absent

- name: enable and start openvpn-client@client_tun
  systemd:
    name: openvpn-client@client_tun
    enabled: true
  notify: restart_openvpn-client@client_tun

- name: enable and start openvpn-client@client_tap
  systemd:
    name: openvpn-client@client_tap
    enabled: true
  notify: restart_openvpn-client@client_tap
...