---
- name: install pg repo
  yum:
    name: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
    update_cache: yes
    state: present

- name: install packages
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - postgresql11
    - postgresql11-server
...