---
all:
  children:
    vlans:
      hosts:
        testServer1:
        testServer2:
        testClient1:
        testClient2:
    bonds:
      hosts:
        inetRouter:
        centralRouter:
...
