---
all:
  children:
    servers:
      hosts:
        master:
          ansible_host: 192.168.11.150
        replica:
          ansible_host: 192.168.11.151
    backups:
      hosts:
        backup:
          ansible_host: 192.168.11.152
...
