---
all:
  children:
    vagrantvms:
      hosts:
        freeipa:
          ansible_host: 192.168.11.117 # FreeIPA server
        client:
          ansible_host: 192.168.11.118 # LDAP (FreeIPA) client
...
