---
all:
  children:
    dir:
      hosts:
        bserver:
          ansible_host: 192.168.11.124
    sd:
      hosts:
        bserver:
          ansible_host: 192.168.11.124
    cons:
      hosts:
        bserver:
          ansible_host: 192.168.11.124
    fd:
      hosts:
        bclient:
          ansible_host: 192.168.11.125
...
