---
- name: Generate an OpenSSL private key for OpenVPN RAS server
  openssl_privatekey:
    path: "{{ pki_ovpn_private_path }}{{ ovpn_ras_private_key_name }}"
    size: "{{ ovpn_private_key_bits }}"

- name: Generate an OpenSSL CSR for OpenVPN RAS server
  openssl_csr:
    path: "{{ pki_ovpn_certs_path }}{{ ovpn_ras_private_key_name }}.csr"
    privatekey_path: "{{ pki_ovpn_private_path }}{{ ovpn_ras_private_key_name }}"
    country_name: "{{ ovpn_country_name }}"
    organization_name: "{{ ovpn_org_name }}"
    email_address: "{{ ovpn_email_addr }}"
    common_name: "{{ ovpn_common_name }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    extended_key_usage:
      - serverAuth

# Заготовка, если ВМ с CA != ВМ с ovpn server
#- name: Copy CSR from client to server
#  synchronize: src=/etc/pki/CA/certs/openvpn_server.csr dest=/etc/pki/CA/certs/openvpn_server.csr
#  delegate_to: server

- name: Generate server certificate signed with my own CA certificate
  openssl_certificate:
    subject:
      CN: "{{ ovpn_common_name }}"
    path: "{{ pki_ovpn_certs_path }}{{ ovpn_ras_cert_name }}"
    privatekey_path: "{{ pki_ovpn_private_path }}{{ ovpn_ras_private_key_name }}"
    csr_path: "{{ pki_ovpn_certs_path }}{{ ovpn_ras_private_key_name }}.csr"
    ownca_path: "{{ pki_CA_certs_path }}{{ CA_cert_name }}"
    ownca_privatekey_path: "{{ pki_CA_private_path }}{{ CA_private_key_name }}"
    provider: ownca
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_strict: true
    extended_key_usage:
      - clientAuth
    extended_key_usage_strict: true
# Заготовка, если ВМ с CA != ВМ с ovpn server
#  delegate_to: server
...