# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :inetRouter => {
    :box_name => "centos/6",
    :net => [
      {adapter: 2, :device => "eth1", auto_config: false, virtualbox__intnet: "router-net"},
      {adapter: 3, :device => "eth2", auto_config: false, virtualbox__intnet: "router-net3"},
      {adapter: 4, :device => "eth3", auto_config: false, virtualbox__intnet: true},
      {adapter: 5, :device => "eth4", auto_config: false, virtualbox__intnet: true},
    ]
  },
  :inetRouter2 => {
    :box_name => "centos/6",
    :net => [
      {ip: '192.168.254.1', adapter: 2, :device => "eth1",   netmask: "255.255.255.252", virtualbox__intnet: "router-net2"},
      {adapter: 3, network: "private_network", :type => 'dhcp' },
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :centralRouter => {
    :box_name => "centos/7",
    :net => [
      {adapter: 2, :device => "eth1", auto_config: false, virtualbox__intnet: "router-net2"},
      {adapter: 3, :device => "eth2", auto_config: false, virtualbox__intnet: "dir-net"},
      {adapter: 4, :device => "eth3", auto_config: false, virtualbox__intnet: "interrouter1-net"},
      {adapter: 5, :device => "eth4", auto_config: false, virtualbox__intnet: "interrouter2-net"},
      {adapter: 6, :device => "eth5", auto_config: false, virtualbox__intnet: "router-net"},
      {adapter: 7, :device => "eth6", auto_config: false, virtualbox__intnet: "router-net3"},
    ]
  },
  :centralServer => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.0.2',   adapter: 2, :device => "eth1",   netmask: "255.255.255.240", virtualbox__intnet: "dir-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :office1Router => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.255.10',  adapter: 2, :device => "eth1",   netmask: "255.255.255.252", virtualbox__intnet: "interrouter1-net"},
      {ip: '192.168.2.1',     adapter: 3, :device => "eth2",   netmask: "255.255.255.192", virtualbox__intnet: "office1dev-net"},
      {ip: '192.168.2.65',    adapter: 4, :device => "eth3",   netmask: "255.255.255.192", virtualbox__intnet: "office1testservers-net"},
      {ip: '192.168.2.129',   adapter: 5, :device => "eth4",   netmask: "255.255.255.192", virtualbox__intnet: "office1mngr-net"},
    ]
  },
  :office1Server => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.2.66',   adapter: 2, :device => "eth1",   netmask: "255.255.255.192", virtualbox__intnet: "office1testservers-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :testServer1 => {
    :box_name => "centos/7",
    :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "office1testservers-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :testServer2 => {
    :box_name => "centos/7",
    :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "office1testservers-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :testClient1 => {
    :box_name => "centos/7",
    :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "office1testservers-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :testClient2 => {
    :box_name => "centos/7",
    :net => [
      {adapter: 2, auto_config: false, virtualbox__intnet: "office1testservers-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
  :office2Router => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.255.6',   adapter: 2, :device => "eth1",   netmask: "255.255.255.252", virtualbox__intnet: "interrouter2-net"},
      {ip: '192.168.1.1',     adapter: 3, :device => "eth2",   netmask: "255.255.255.128", virtualbox__intnet: "office2dev-net"},
      {ip: '192.168.1.129',   adapter: 4, :device => "eth3",   netmask: "255.255.255.192", virtualbox__intnet: "office2testservers-net"},
      {ip: '192.168.1.193',   adapter: 5, :device => "eth4",   netmask: "255.255.255.192", virtualbox__intnet: "office2hw-net"},
    ]
  },
  :office2Server => {
    :box_name => "centos/7",
    :net => [
      {ip: '192.168.1.130',   adapter: 2, :device => "eth1",   netmask: "255.255.255.192", virtualbox__intnet: "office2testservers-net"},
      {adapter: 3, auto_config: false, virtualbox__intnet: true},
      {adapter: 4, auto_config: false, virtualbox__intnet: true},
      {adapter: 5, auto_config: false, virtualbox__intnet: true},
    ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
          end

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
          vb.customize ["modifyvm", :id, "--cpus", "1"]
          vb.name = boxname.to_s
          end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
          end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/22 -o eth0 -j MASQUERADE
            SHELL

        when "inetRouter2"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            ip route add 192.168.0.0/24 via 192.168.254.2 dev eth1
            ip route add 192.168.1.0/24 via 192.168.254.2 dev eth1
            ip route add 192.168.2.0/24 via 192.168.254.2 dev eth1
            ip route add 192.168.255.4/30 via 192.168.254.2 dev eth1
            ip route add 192.168.255.8/30 via 192.168.254.2 dev eth1
            SHELL

        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            #ip route delete default 2>&1 >/dev/null || true
            SHELL

        when "office1Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            ip route delete default 2>&1 >/dev/null || true
            ip address add 192.168.2.193/26 dev eth4:1
            ip link set eth4:1 up
            ip route add 192.168.0.0/24 via 192.168.255.9 dev eth1
            ip route add 192.168.1.0/24 via 192.168.255.9 dev eth1
            ip route add 192.168.255.4/30 via 192.168.255.9 dev eth1
            ip route add 0.0.0.0/0 via 192.168.255.9 dev eth1
            SHELL

        when "office2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            sysctl net.ipv4.conf.all.forwarding=1
            ip route delete default 2>&1 >/dev/null || true
            ip route add 192.168.0.0/24 via 192.168.255.5 dev eth1
            ip route add 192.168.2.0/24 via 192.168.255.5 dev eth1
            ip route add 192.168.255.8/30 via 192.168.255.5 dev eth1
            ip route add 0.0.0.0/0 via 192.168.255.5 dev eth1
            SHELL

        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route delete default 2>&1 >/dev/null || true
            ip route add 0.0.0.0/0 via 192.168.0.1 dev eth1
            SHELL

        when "office1Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route delete default 2>&1 >/dev/null || true
            ip route add 0.0.0.0/0 via 192.168.2.65 dev eth1
            SHELL

        when "office2Server"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            ip route delete default 2>&1 >/dev/null || true
            ip route add 0.0.0.0/0 via 192.168.1.129 dev eth1
            SHELL
        end
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible_repo/startall.yml"
    ansible.become = "true"
  end

end
