# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :elk => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.121',
  },
  :log => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.120',
  },
  :web => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.119',
  },
}

Vagrant.configure("2") do |config|

      config.trigger.before :up do |trigger|
            trigger.info = "Pre-up trigger..."
            trigger.run = {path: "./provision_service/keygen.sh"}
      end

      MACHINES.each do |boxname, boxconfig|

      	config.vm.define boxname do |box|

                  box.vm.box = boxconfig[:box_name]
                 	box.vm.host_name = boxname.to_s

                  box.vm.network "private_network", ip: boxconfig[:ip_addr]
                        default_router = "192.168.11.1"

      	  	case boxname.to_s
                        when "web"
                        box.vm.provider :virtualbox do |vb|
                              vb.customize ["modifyvm", :id, "--memory", "384"]
                              vb.customize ["modifyvm", :id, "--cpus", "1"]
                              vb.name = boxname.to_s
                        end
                        box.vm.provision "shell", run: "always", inline: <<-SHELL
                              mkdir -p ~root/.ssh
                              cp ~vagrant/.ssh/auth* ~root/.ssh
                              cat /vagrant/id_rsa.pub | awk '{print $1,$2}' >> /root/.ssh/authorized_keys
                              echo "add default via #{default_router}"
                              ip route delete default 2>&1 >/dev/null || true
                              ip route add default via #{default_router} metric 1
                        SHELL
                        box.trigger.after :up do |trigger|
                              trigger.info = "nginx - Post-up trigger..."
                              trigger.run = { path: "./provision_service/web_after_up.sh" }
                        end

                        when "log"
                        box.vm.provider :virtualbox do |vb|
                              vb.customize ["modifyvm", :id, "--memory", "384"]
                              vb.customize ["modifyvm", :id, "--cpus", "1"]
                              vb.name = boxname.to_s
                        end
                        box.vm.provision "shell", run: "always", inline: <<-SHELL
                              mkdir -p ~root/.ssh
                              cp ~vagrant/.ssh/auth* ~root/.ssh
                              cat /vagrant/id_rsa.pub | awk '{print $1,$2}' >> /root/.ssh/authorized_keys
                              echo "add default via #{default_router}"
                              ip route delete default 2>&1 >/dev/null || true
                              ip route add default via #{default_router} metric 1
                        SHELL
                        box.trigger.after :up do |trigger|
                              trigger.info = "journal - Post-up trigger..."
                              trigger.run = { path: "./provision_service/log_after_up.sh" }
                        end

                        when "elk"
                        box.vm.provider :virtualbox do |vb|
                              vb.customize ["modifyvm", :id, "--memory", "4096"]
                              vb.customize ["modifyvm", :id, "--cpus", "4"]
                              vb.name = boxname.to_s
                        end
                        box.vm.provision "shell", run: "always", inline: <<-SHELL
                              mkdir -p ~root/.ssh
                              cp ~vagrant/.ssh/auth* ~root/.ssh
                              cat /vagrant/id_rsa.pub | awk '{print $1,$2}' >> /root/.ssh/authorized_keys
                              echo "add default via #{default_router}"
                              ip route delete default 2>&1 >/dev/null || true
                              ip route add default via #{default_router} metric 1
                        SHELL
                        box.trigger.after :up do |trigger|
                              trigger.info = "elk - Post-up trigger..."
                              trigger.run = { path: "./provision_service/elk_after_up.sh" }
                        end
                  end
            end
      end
      
      config.vm.provision "ansible" do |ansible|
            ansible.playbook = "./ansible_repo/startall.yml"
            ansible.inventory_path = "./ansible_repo/inventory_dev/hosts.yml"
      end
end
