# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']

MACHINES = {
  :server1 => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.113',
  },
  :ansible => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.114',
  },
}

Vagrant.configure("2") do |config|

# Подключаться будем по SSH ключам, которые будут генерироваться при создании виртуалок.
# Не выкладывать же их в git :)

	config.trigger.before :up do |trigger|
    		trigger.info = "Generating keys..."
		trigger.run = {path: "keygen.sh"}
  		end

  MACHINES.each do |boxname, boxconfig|
	  config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "256"]
          vb.name = boxname.to_s
          end
      box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
      SHELL

      case boxname.to_s
      when "ansible"

# На машину с которой будем управлять другими машинами установим ansible.
# Скопируем туда ключи и добавим целевую машину в известные.
# Также пропишем целевую машину в hosts, пока у нас нет dns.
# Выполним роль и проверим ответ nginx с порта 8080 целевой машины.

	  box.vm.provision "shell", run: "always", inline: <<-SHELL
          yum install epel-release -y -q 2>/dev/null
          yum install ansible vim -y -q 2>/dev/null
          cp /vagrant/id_rsa /home/vagrant/.ssh/
          chown vagrant:vagrant /home/vagrant/.ssh/id_rsa 
          chmod 0600 /home/vagrant/.ssh/id_rsa
          cp /vagrant/id_rsa /root/.ssh/
          chown root:root /root/.ssh/id_rsa 
          chmod 0600 /root/.ssh/id_rsa
	  echo "192.168.11.113  server1" >> /etc/hosts
	  ssh-keyscan -t rsa server1 >> /home/vagrant/.ssh/known_hosts 2>/dev/null
	  ssh-keyscan -t rsa server1 >> /root/.ssh/known_hosts 2>/dev/null
	  cd /vagrant/ansible_repo/
	  ansible-playbook start.yml
	  sleep 3
	  curl http://server1:8080/ 2>/dev/null
          SHELL

      when "server1"
# Тут просто добавим ключи, чтобы не ломиться по паролю.
        box.vm.provision "shell", run: "always", inline: <<-SHELL
          cat /vagrant/id_rsa.pub | awk '{print $1,$2}' >> /home/vagrant/.ssh/authorized_keys
          SHELL
      end

      end
   end
end
